# Generated by Django 2.2 on 2019-04-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonio',
            options={'ordering': ['-created'], 'verbose_name': 'Testimonio', 'verbose_name_plural': 'Testimonios'},
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='imagen',
            field=models.ImageField(upload_to='testimonials', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='mensaje',
            field=models.TextField(verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
