# Generated by Django 2.2 on 2019-04-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonios', '0002_auto_20190426_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonio',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
    ]
